### ISSUE TITLE
No error but exit code 1

### ISSUE THREAD

**Issue by anykeyh** [veelenga/ameba#101]
Hello, since update to 0.28 for [Clear](https://github.com/anykeyh/clear/pull/113) my build fail on call to ameba, both in dev and travis environment, while all the checks are passed:

Output of my dev env:

```bash
$ bin/ameba src
Inspecting 122 files.

..........................................................................................................................

Finished in 497.43 milliseconds 

122 inspected, 0 failures.
04:06 me@x1e ~/W/clear crystal-28 …1 ./rw
$ echo $status                                                                                                                                     1
```

(note: `echo $status` stands for `echo $?` in fish)

Output of the TravisCI build: https://travis-ci.org/anykeyh/clear/builds/524188305#L509

**Comment by veelenga** [comment]
This is a regression introduced in #100.

Use previous commit, it is also compatible with Crystal 0.28

`c95ea297bd24aff0dbbe64a14c8feb2db12bb4c3`
