### ISSUE TITLE
[0.29.0] undefined method 'name_column_number' for Crystal::Def

### ISSUE THREAD

**Issue by Blacksmoke16** [veelenga/ameba#103]
https://github.com/crystal-lang/crystal/pull/7827

Changed the method `name_column_number` to `name_location`, so currently Ameba doesn't compile against master.  Just a heads up for the upcoming `0.29.0` release.

**Comment by veelenga** [comment]
Thanks. Does this block you? I can prepare a branch which will be compatible with crystal master and will wait for the new crystal release.

**Comment by Blacksmoke16** [comment]
Naw I can wait.  Thanks tho.

**Comment by bcardiff** [comment]
I wouldn't mind having a branch that will run against Crystal head. 😅 
It would be helpful to completely test lucky before the release.

**Comment by veelenga** [comment]
Okay, I will create such a branch and let you know.

**Comment by veelenga** [comment]
@bcardiff 

* https://github.com/veelenga/ameba/tree/crystal-head

Will maintain it. Added crystal-nightly and periodical builds on Travis (for now, it fails because of https://github.com/crystal-lang/crystal/issues/5836)

**Comment by bcardiff** [comment]
Cool! Thanks! A fix for the nightly issue is no the way 💪
