### ISSUE TITLE
Incorrect detection of Performance/FirstLastAfterFilter on custom class

### ISSUE THREAD

**Issue by raymanoz** [veelenga/ameba#111]
When there is no `find` method on a class, ameba is still suggests using it

Example:
```
class Example
  def select
    yield "Hello, "
    self
  end

  def first
    puts "World!"
  end
end

print Example.new.select { |a| print a }.first
```

Yields:
```
[C] Performance/FirstLastAfterFilter: Use `find {...}` instead of `select {...}.first`
```

**Comment by veelenga** [comment]
Ameba is only about static code analysis, it knows nothing about semantics and the type of the object the method sent to. In other words, right now, it is not possible to correctly process your case.

I am thinking about disabling by default these performance rules for a while. Once we do semantics analysis, we will be able to switch that back.

**Comment by raymanoz** [comment]
ok, no problem.
