### ISSUE TITLE
Comparison to boolean rule should be removed?

### ISSUE THREAD

**Issue by veelenga** [veelenga/ameba#12]
```
# A rule that disallows comparison to booleans.
#
# For example, these are considered invalid:
#
# ```crystal
# foo == true
# bar != false
# false === baz
# ```
# This is because these expressions evaluate to `true` or `false`, so you
# could get the same result by using either the variable directly, or negating
# the variable.
```

As said [here](https://github.com/veelenga/ameba/commit/6d9f1c67ed30920c49db9c699ac0625523ebcac9#comments), comparison to booleans some times makes sense in Crystal:

```crystal
a : Bool | Nil = some_value

if a == true
end

if a == false
end

if a == nil
end
```

It is not possible to check a type of the variable and implement it properly, so probably this rule just need to be removed.

**Comment by hugoabonizio** [comment]
Maybe this use-case is better suited on a ```case``` statement instead of ```if```s anyway.

**Comment by veelenga** [comment]
I believe not only on a `case`:

```crystal
# `a` somewhere declared as Bool | Nil and than used
if a == true
  # we want to be sure it is not nil, but is true
end
```

I found it is possible to use Crystal's compiler and infer types and handle this 🎉 
And it may be useful for some other rules as well

**Comment by veelenga** [comment]
This rule is disabled by default in f4f401d56f4c21b3a4ff515e0cdb0ee9ca432a37
