### ISSUE TITLE
Inline rule disabling

### ISSUE THREAD

**Issue by taylorfinnell** [veelenga/ameba#28]
Is it possible to do something like follows

```
# ameba:disable LargeNumbers
time = Time.epoch(1483859302)
```

I think it may be possible to add, if you're interested, by using the `#doc` object on the AST node

Thanks!

**Comment by veelenga** [comment]
@taylorfinnell thanks for the interest.

For a moment it is possible to excluded specific files from the rule and disable specific rules using a config file `.ameba.yml`. You can generate one via cli `ameba --gen-config` and adjust afterwards.

Inline disabling/adjusting is a rubocop's feature i would like to see in ameba as well. Yes, that's doable and planned to be added in future. And you are right regarding the approach, so traversing AST and visiting comments should be a way to do that...
