### ISSUE TITLE
Ameba compilation is too slow

### ISSUE THREAD

**Issue by faustinoaq** [veelenga/ameba#31]
Hi @veelenga, I think we should remove the `--release` flag here 👉 https://github.com/veelenga/ameba/blob/master/Makefile#L6

Optimizations are very expensive on some environments. Compiling ameba using `--release` after executing `shards install` changes deploy time from seconds to minutes in some cases

Ameba is a CLI tool and is still very fast without `--release` flag. So, I think we are spending extra compilation time with no gain.

**Comment by veelenga** [comment]
Included in https://github.com/veelenga/ameba/releases/tag/v0.4.1
