### ISSUE TITLE
Introduce severity

### ISSUE THREAD

**Issue by veelenga** [veelenga/ameba#39]

**Comment by wisn** [comment]
@veelenga could you elaborate? I think I would try to contributes

**Comment by veelenga** [comment]
@wisn cool and thanks for the interest.

- [ ] Each rule should have it's own severity
- [ ] Severity could be one of `error`, `warning`, `refactoring`
- [ ] Severity should be inferred by the name and category by default. For example:
  
  * [Layout/*](https://github.com/veelenga/ameba/tree/master/src/ameba/rule/layout) - refactoring
  * [Metrics/*](https://github.com/veelenga/ameba/tree/master/src/ameba/rule/metrics) - refactoring
  * [Performance/*](https://github.com/veelenga/ameba/tree/master/src/ameba/rule/performance) - refactoring
  * [Style/*](https://github.com/veelenga/ameba/tree/master/src/ameba/rule/style) - refactoring
  * [Lint/*](https://github.com/veelenga/ameba/tree/master/src/ameba/rule/lint) - warning
  * [Lint/Syntax](https://github.com/veelenga/ameba/blob/master/src/ameba/rule/lint/syntax.cr) - error

for now we will have only one rule with `error` severity but it can be changed later.
  
- [ ] Severity should be customizable via config
- [ ] User should be able to run only rules which have some severity: `ameba --fail-level SEVERITY`

For example:

* `ameba --fail-level refactoring` - default and current behaviour. Fails if at least one rule of severity `refactoring`, `warning` or `error` fails
* `ameba --fail-level warning` - fails if at least one of rule of severity `warning` or `error` fails
* `ameba --fail-level error` - fails if at least one rule of severity `error` fails

Does this makes sense to you?

**Comment by wisn** [comment]
@veelenga Thanks for the explanation and sorry for the late reply.

> Does this make sense to you?

Yes.

**Comment by veelenga** [comment]
@wisn sorry, i have already submitted PR for this #100 

will finish that soon

**Comment by wisn** [comment]
@veelenga no worries :D
