### ISSUE TITLE
Incorrect detection of useless assignment when nested?

### ISSUE THREAD

**Issue by fgimian** [veelenga/ameba#66]
Hey there, thanks so much for writing Ameba, love it! 😄 

I'm seeing a strange behaviour which I suspect might be a bug; given this code:

```crystal
    ...
    def process
      # Determine the pip executable
      executable : String? = nil

      if @virtualenv
        ["pip", "pip3", "pip2"].each do |pip|
          pip_path = File.join([@virtualenv.as(String), "bin", pip])
          if File.exists?(pip_path)
            executable = pip_path
            break
          end
        end

        unless executable
          raise ActionProcessingError.new(
            "Unable to find a pip executable in the virtualenv supplied"
          )
        end
   ...
```

Ameba says:

```
UselessAssign: Useless assignment to variable `executable`
```

However as you can see, I use `executable` in the `unless` block.   By declaring `executable : String? = nil` outside the `if` statement block, the value of `executable` is retained outside of the nested block.

Am I perhaps missing something or is this a bug in Ameba?

Thanks heaps
Fotis

**Comment by fgimian** [comment]
Here's a shorter self-contained little test script that demonstrates the problem:

```crystal
name : String? = nil
age = 30

[10, 20, 30].each do |test_age|
  if test_age == age
    name = "Fotis"
  end
end

if name
  puts "Hello there #{name}"
end
```

Cheers
Fotis

**Comment by veelenga** [comment]
Thanks for reporting.

Reduced:

```crystal
name : String? = nil

1.times do
  name = "Fotis"
end

name
```

**Comment by fgimian** [comment]
Thank you so much for fixing this so quickly @veelenga! 😄
