### ISSUE TITLE
Potential bug with throwaway variables?

### ISSUE THREAD

**Issue by fgimian** [veelenga/ameba#67]
Hey there, I'm pretty certain this is a little bug, can you confirm?

```crystal
data = [{1, "a"}, {2, "b"}, {3, "c"}]

data.each do |_, string|
  data.each do |number, _|
    puts string, number
  end
end
```

And the error is:

```
test.cr:4:25
Lint/ShadowingOuterLocalVar: Shadowing outer local variable `_`
```

However `_` should be used for unused values should it not and thus shadowing this particular variable shouldn't be a problem?

Kindest Regards
Fotis

**Comment by veelenga** [comment]
Interesting. Actually, `_` was ignored by Crystal parser before.

**Comment by fgimian** [comment]
No worries, thanks so much for repairing it so quickly! 😄
