### ISSUE TITLE
Docker image for (Gitlab) CI?

### ISSUE THREAD

**Issue by aisrael** [veelenga/ameba#68]
I'd like to use ameba as part of a Gitlab CI build pipeline. While I could use an internal Docker image for this step, I think a public, `ameba/ameba` image on Docker Hub would be useful to others as well.

Be glad to work on this and submit a PR if the maintainers agree.

**Comment by veelenga** [comment]
Agree, for sure. Please go ahead and submit the PR ❤️

**Comment by veelenga** [comment]
@aisrael any progress with it? If not, i think i can handle it

**Comment by aisrael** [comment]
I have a `Dockerfile` (based on `alpine:3.8`) ready that builds and can run `ameba`, but my issue is that to use it, you have to use a volume mount:

```
$ docker run -v $(pwd):/src ameba
```

I don't think there's any other way around it. If that's acceptable, I'll raise the PR.

**Comment by veelenga** [comment]
Please open PR and we will discuss it. Thanks in advance
