### ISSUE TITLE
[Feature Request] rule to find issues in string interpolation 

### ISSUE THREAD

**Issue by bararchy** [veelenga/ameba#71]
Try and see if var `e` was defined and then called in "{e.inspect_with_backtrace}" and notify "#" is missing before interpolation.
etc..

**Comment by veelenga** [comment]
Yeah, most likely, but not guaranteed:

```
begin
  ...
rescue e
  logger "{e}: #{e}"
end

```

**Comment by Sija** [comment]
Seems like pretty obscure use case for a feature. I haven't seen such problem in RL even once. Following that line of reasoning we'd have to add new rules for every possible typo in the code...

**Comment by straight-shoota** [comment]
Yes, that's something that should be covered by specs.

**Comment by Sija** [comment]
IMHO there's nothing actionable here, I vote for closing.

**Comment by bararchy** [comment]
@veelenga No need, you have technically explained why this does not make sense and I agree :)
