### ISSUE TITLE
Renaming to crlint

### ISSUE THREAD

**Issue by vladfaust** [veelenga/ameba#81]
I'm just raising a question. crlint looks more consistent in the world of tools like eslint, jslint, stylelint etc. If a developer sees "crlint", he would immediately assume that it's a linter for "cr", which is better than abstract Ameba thing. The same for `.crlint.yaml` or `.crlint.json`.

**Comment by veelenga** [comment]
Thanks, but this pattern name is not an etalon.

credo, dogma, rubocop, checkstyle, flake8, xo etc...

Also, i don't like `crlint` :)

**Comment by vladfaust** [comment]
Alright then!
