### ISSUE TITLE
Useless assignment when using kilt templates

### ISSUE THREAD

**Issue by stakach** [veelenga/ameba#84]
For example, this in a crystal file

```
data = "for template"
Kilt.render(template_path.ecr)
```

and a template that looks like this:

```
<p>some data <%= data %></p>
```

results in `UselessAssign: Useless assignment to variable 'data'`

**Comment by veelenga** [comment]
This is expected and there is no way to handle this situation. 

You can disable `UselessAssign` rule for this file.

**Comment by stakach** [comment]
Thanks! Worked a charm

**Comment by Blacksmoke16** [comment]
@veelenga I'm assuming there is also no fix for `ECR` rendered templates?

**Comment by veelenga** [comment]
@Blacksmoke16 unfortunately, there is no robust solution that could work in all situation.
