### ISSUE TITLE
[Feature Request] Cyclomatic Complexity

### ISSUE THREAD

**Issue by hanneskaeufler** [veelenga/ameba#91]
I'd love for ameba to report on overly complex methods. I guess [cyclomatic complexity](https://en.wikipedia.org/wiki/Cyclomatic_complexity) needs no introduction.

Would probably make sense to open a `Metrics/CyclomatixComplexity` group for that.

**Comment by hanneskaeufler** [comment]
I might go ahead and take a look at implementing this at some point in time, just getting the idea out there and see if it's something you thought about? No promises or timeline for my crack at it though :)

**Comment by veelenga** [comment]
It will be a great addition, for sure.

Let us know if you start working on that, otherwise I can take a look later too.

**Comment by Sija** [comment]
Can be closed already, yay! :)

**Comment by iambudi** [comment]
How to turn off this "Cyclomatic Complexity" checking? When using ameba vscode extension, this checking makes the code looks scary with red underlined 😃.
This feature should be optional.

**Comment by Blacksmoke16** [comment]
@iambudi See https://github.com/veelenga/ameba#configuration

**Comment by veelenga** [comment]
This is a bug in the vs code ext https://github.com/veelenga/vscode-crystal-ameba/issues/3
