### ISSUE TITLE
Some doubts

### ISSUE THREAD

**Issue by Hentioe** [veelenga/ameba#95]
I have two failures. I don't know how to solve it. I hope I can get help.

## Case a tuple

````
Lint/LiteralInCondition: Literal value found in conditional
> case {index, line}
  ^
````

Sample code:

```` crystal
private def v0_msg_spec(message_lines, index = 0, line = String.new)
  case {index, line}
  when {1, ""}
  else
  end
end
````

## There are multiple local variables in the condition

````
Lint/UselessAssign: Useless assignment to variable `proto`
> if (token = env.request.headers["Token"]?) && (proto = env.request.headers["Proto"]?)
                                                 ^
````

Sample code:

```` crystal
post "/api/test" do |env|
  if (token = env.request.headers["Token"]?) && (proto = env.request.headers["Proto"]?)
    # Use token and proto variables
  end
end
````

😀 Especially the second one, will it be a bug?

**Comment by veelenga** [comment]
First one is a bug.

The second one - I can't reproduce. I noticed you don't use the `proto` var in this sample:

https://github.com/fotify/fotify-lite/blob/b28d9a241db376c128bba788eee2c7fa1694d7ff/src/fotify/router/api.cr#L42-L52

Thanks for posting.

**Comment by Hentioe** [comment]
Yes, my `proto` variable is not used, which is why. I am very sorry that I didn’t notice it.

What surprised me was that you actually looked through my code and found it. Very ashamed 😅

**Comment by veelenga** [comment]
No problem. I will fix the issue reported in the first example. Thanks
